### ISSUE TITLE
後臺測試

### ISSUE THREAD

**Issue by creatopgrace** [creatop/actron-csr#7]
IE9以上測試沒問題

**Comment by creatopgrace** [comment]
後臺問題  @wucindy 
(版面問題 使用版本IE9以上)
1.(社會責任裡面)新增頁面那一排都黏在一起
![image](https://cloud.githubusercontent.com/assets/20021057/16441777/2f9bc742-3e00-11e6-8ec0-bae978c6a919.png)
2.送出訊息時跑版
![image](https://cloud.githubusercontent.com/assets/20021057/16442005/7679f296-3e01-11e6-8ed0-8ad4fdd1297b.png)
3.editor 區塊消失，不能上
![image](https://cloud.githubusercontent.com/assets/20021057/16442311/3cc22228-3e04-11e6-8f83-dc5ba47ee11a.png)
4.最新消息預設圖設定  跑版
![image](https://cloud.githubusercontent.com/assets/20021057/16442350/8acbd874-3e04-11e6-8963-1dd7bb40f8c2.png)

(修改的地方)
1.誠信經營裡面有一個連結設定，但裡面次選單是聯絡我們 (有點奇怪，能調嗎?)
![image](https://cloud.githubusercontent.com/assets/20021057/16442446/3067399a-3e05-11e6-912e-db0d86055d61.png)
後臺有兩個誠信經營可以連結  (我覺得可以把外面的拿掉)
![image](https://cloud.githubusercontent.com/assets/20021057/16443156/b0990ffe-3e09-11e6-9cad-cf5c046351af.png)

3.問券調查有少做功能
  (1) 請問您的身分是?(下面選項可以單一新增)
  (2) 下面的問題選項可以往後新增
       ![image](https://cloud.githubusercontent.com/assets/20021057/16442865/e6edfd50-3e07-11e6-9c65-5cc75bd02be8.png)
      開欄位"議題類別和說明"
      
      ![image](https://cloud.githubusercontent.com/assets/20021057/16442979/9b00dcf4-3e08-11e6-95e6-e9571e1e67b0.png)
      後面的關注度寫死

4.點首頁永續報告書連結到本機?
![image](https://cloud.githubusercontent.com/assets/20021057/16443107/61dfc74a-3e09-11e6-850d-0026e5661fca.png)

5.那時候說不填也可以送出訊息 (可以做嗎?)
![image](https://cloud.githubusercontent.com/assets/20021057/16443217/0ea3119e-3e0a-11e6-9be9-84d0a2d39dfc.png)

6.檔案下載的地方可以在加一個連結嗎?(檔案太大可以用連結)
![image](https://cloud.githubusercontent.com/assets/20021057/16443300/9016052e-3e0a-11e6-8e75-5159f561428b.png)

**Comment by creatopgrace** [comment]
@creatopsean 
客戶說想要以後可以新增的功能
[](http://mars/actron/chinese/csr/report/questionnaire.php?dpid=1)

**Comment by creatopgrace** [comment]
## 後臺圖片尺寸標註修改 @wucindy 有空幫我改

1. 社會企業責任/經營者的話/修改
     ![image](https://cloud.githubusercontent.com/assets/20021057/16473973/49a96540-3ea5-11e6-857e-92d9a40681db.png)
     小圖尺寸 / 90X90
     情境圖尺寸 / 1680X400

2. 最新消息預設圖設定 (最新消息的editor 也小大小圖 記得改)
    小圖 / 180X180
    大圖 / 590X230

3. 檔按下載
    圖片尺寸 / 230X330

**Comment by wucindy** [comment]
下列己修好:
1.editor區塊無法編輯
2.問卷
3.檔案下載新增URL連結欄位
4.誠信經營刪除
5.圖片svg檔無法顯示

**Comment by creatopgrace** [comment]
## news頁面有點奇怪

@wucindy 
**1.一開始沒有往下滑應該是四個區塊**
![image](https://cloud.githubusercontent.com/assets/20021057/16475664/f24884ee-3eb2-11e6-9c16-69ddbadc19fa.png)

**2.上傳功能和選大圖都沒什麼問題，但問題就是選小圖會讀不到圖片**

**Comment by wucindy** [comment]
1.前端News
2.幸福企業情境圖
3.後端排序問題
4.EDIT修改無效問題
以上己解決
