### ISSUE TITLE
後臺圖片尺寸標註修改

### ISSUE THREAD

**Issue by creatopgrace** [creatop/actron-csr#8]
## 後臺圖片尺寸標註修改 @wucindy 有空幫我改

1. 社會企業責任/經營者的話/修改
     ![image](https://cloud.githubusercontent.com/assets/20021057/16473973/49a96540-3ea5-11e6-857e-92d9a40681db.png)
     小圖尺寸 / 90X90
     情境圖尺寸 / 1680X400

2. 最新消息預設圖設定 (最新消息的editor 也小大小圖 記得改)
    小圖 / 180X180
    大圖 / 590X230

3. 檔按下載
    圖片尺寸 / 230X330

**Comment by creatopsean** [comment]
## 後台文字更改

**檔案下載改成經營報告書**

**Comment by wucindy** [comment]
1.尺寸標注
 2.檔案下載改成經營報告書
   顯示方式改成下載方式
   開啟新視窗改成本地下載 / 置幻本頁改成外部下載
已修
